### ISSUE TITLE
Question: How can I use this ODataAuthorization to hide a NavigationProperty?

### ISSUE THREAD

**Issue by ika18** [bytefish/ODataAuthorization#1]
Hi there,
I want to hide a NavigationProperty even if the client-side use `$expand`.
For example, there is a User object that has Address navigation, I want to hide the Address property without preventing reading the User, it looks like
```json
{
  "id": 1,
  "name": "ika",
  "address": null
}
```

**Comment by bytefish** [comment]
@ika18 Do you have a small example project, that we could use to reproduce the issue and see how to fix it?

**Comment by ika18** [comment]
Hi @bytefish , thank you for your reply.
Sure, I just made a small [project](https://github.com/ika18/ODataAuthorization.Sample).

In this sample, there are two users, admin and user. 
And there are two simple models, product and address. The product has a navigation property that navigates to the address.
I want to hide a navigation property's detail for the user using `$expand=adress` in the query.

Could this be config by ODataAuthorization?

And edm model could be found [here](https://github.com/ika18/ODataAuthorization.Sample/blob/main/JwtAuthenticationSample/Models/AppEdmModel.cs)

**Comment by bytefish** [comment]
Great job! This saves a lot of time. 👍 I will take a look and we will see what’s required to make this work.

**Comment by bytefish** [comment]
@ika18 It's not directly related to the issue at hand, I didn't have the time yet.

The funny thing is, that some days ago I thought about how to provide better authorization for OData-based applications. My biggest issue with OData is, that it's quite hard to limit what a user is allowed to query for. It's concerning, that a user probably expands a Navigation Property and can suddenly query half the database, even if he isn't meant to access it. 

I want to understand how on earth applications like the Microsoft Graph API are able to distinguish between "my data" and "all data", when querying a dataset. It's hard to achieve this with Role-based Authorization alone. So most probably these implementations have some kind of Permission Service in-between to resolve the complex relationships for user permissions. 

So I have taken a look at the Google Zanzibar Paper:

* https://www.bytefish.de/blog/relationship_based_acl_with_google_zanzibar.html

Maybe you are interested and we could spark a discussion. As for the issue at hand, I will take a look as soon as I have some hours off...

**Comment by ika18** [comment]
> @ika18 It's not directly related to the issue at hand, I didn't have the time yet.
> 
> The funny thing is, that some days ago I thought about how to provide better authorization for OData-based applications. My biggest issue with OData is, that it's quite hard to limit what a user is allowed to query for. It's concerning, that a user probably expands a Navigation Property and can suddenly query half the database, even if he isn't meant to access it.
> 
> I want to understand how on earth applications like the Microsoft Graph API are able to distinguish between "my data" and "all data", when querying a dataset. It's hard to achieve this with Role-based Authorization alone. So most probably these implementations have some kind of Permission Service in-between to resolve the complex relationships for user permissions.
> 
> So I have taken a look at the Google Zanzibar Paper:
> 
> * https://www.bytefish.de/blog/relationship_based_acl_with_google_zanzibar.html
> 
> Maybe you are interested and we could spark a discussion. As for the issue at hand, I will take a look as soon as I have some hours off...

Hi @bytefish , I have the exact same issue as you. Yes, the OData gives the very convenience on query data from the client. That helps developers save a lot of time to make CURD API. However, I find it hard to customize the permission. And I am very curious about how Microsoft uses OData with RBAC to make a CRM or Microsoft Graph API.

I appreciate that you sent me your blog. I will definitely read that.

**Comment by bytefish** [comment]
@ika18 I confirm, that there is a bug when checking the Permissions. Let's see...

I started by adding the Navigation Restriction for the `Products/Address` in the `AppEdmModel`, like this:

```csharp
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;
using Microsoft.OData.ModelBuilder;

namespace JwtAuthenticationSample.Models;

public class AppEdmModel
{
    public static IEdmModel GetModel()
    {
        var builder = new ODataConventionModelBuilder();

        // ...

        products.HasNavigationRestrictions()
            .HasRestrictedProperties(props => props
                .HasNavigationProperty(new EdmNavigationPropertyPathExpression("Products/Address"))
                    .HasReadRestrictions(r => r.HasPermissions(p => p.HasSchemeName("Scheme").HasScopes(s => s.HasScope("Products.ReadAddress")))));


        return builder.GetEdmModel();
    }
}
```

Next I wrote a small Powershell Script to run Queries:

```powershell
<#
.SYNOPSIS
    Example Script for restricting Navigation Properties using the 
    ODataAuthorization library.
.DESCRIPTION
    This script obtains a valid token and proceeds to perform requests to
    the API.
.NOTES
    File Name      : ODataQueries.ps1
    Author         : Philipp Wagner
    Prerequisite   : PowerShell
    Copyright 2023 - MIT License
#>

# Perform /Auth/login to obtain the JWT with Requested Scopes
$authRequestBody = @{
    Email = "admin@admin.com"
    Password = "123456"
    RequestedScopes = "Products.Read Products.ReadByKey"
}

$authRequestParameters = @{
    Method = "POST"
    Uri = "http://localhost:5124/Auth/login"
    Body = ($authRequestBody | ConvertTo-Json) 
    ContentType = "application/json"
}

# Invoke the Rest API
$authRequestResponse = Invoke-RestMethod @authRequestParameters

# Extract JWT from the JSON Response 
$authToken = $authRequestResponse.token

# The Auth Header needs to be sent for any additional OData request
$authHeader = @{
    Authorization = "Bearer $authToken"
}

# OData Query 1: All Products
$allProductsResponse = Invoke-RestMethod -Uri "http://localhost:5124/odata/Products" -Headers $authHeader 

Write-Host "OData Query #1: http://localhost:5124/odata/Products"
Write-Host $allProductsResponse.value | ConvertTo-Json

# Write-Host " "

# OData Query 1: All Products
$customersWithAddressResponse = Invoke-RestMethod -Uri "http://localhost:5124/odata/Products?`$expand=Address" -Headers $authHeader 

Write-Host "OData Query #2: http://localhost:5124/odata/Products(`$expand=Address)"
Write-Host $customersWithAddressResponse.value | ConvertTo-Json
Write-Host "`n"
Write-Host "`n"
```

The expected result is, that the second query should return a `403 Forbidden` Exception, but instead it returns ...

```
OData Query #1: http://localhost:5124/odata/Products

@{Id=1; Name=Macbook M1; Price=3000; AddressId=1} @{Id=2; Name=Macbook M2; Price=3500; AddressId=1} @{Id=3; Name=iPhone 14; Price=1400; AddressId=1}

-------------

OData Query #2: http://localhost:5124/odata/Products($expand=Address)

@{Id=1; Name=Macbook M1; Price=3000; AddressId=1; Address=} @{Id=2; Name=Macbook M2; Price=3500; AddressId=1; Address=} @{Id=3; Name=iPhone 14; Price=1400; AddressId=1; Address=}
```

This is wrong, the second query should be forbidden. Now if I comment out the first query in the script like this:

```powershell
# OData Query 1: All Products
# $allProductsResponse = Invoke-RestMethod -Uri "http://localhost:5124/odata/Products" -Headers $authHeader 
#
# Write-Host "OData Query #1: http://localhost:5124/odata/Products"
# Write-Host $allProductsResponse.value | ConvertTo-Json

# Write-Host " "

# OData Query 1: All Products
$customersWithAddressResponse = Invoke-RestMethod -Uri "http://localhost:5124/odata/Products?`$expand=Address" -Headers $authHeader 

Write-Host "OData Query #2: http://localhost:5124/odata/Products(`$expand=Address)"
Write-Host $customersWithAddressResponse.value | ConvertTo-Json
Write-Host "`n"
Write-Host "`n"
```

And if I ...

1. Restart the Backend
2. Re-Run the Script

We get the following behavior:

```
PS C:\Users\philipp\source\repos\bytefish\ODataAuthorization.Sample\Powershell> .\ODataQueries.ps1
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Users\philipp\source\repos\bytefish\ODataAuthorization.Sample\Powershell\ODataQueries.ps1:49 char:33
+ ... sResponse = Invoke-RestMethod -Uri "http://localhost:5124/odata/Produ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

OData Query #2: http://localhost:5124/odata/Products($expand=Address)
```

Which is what we expect.

So clearly, the library (or ASP.NET Core) caches the Permission Evaluator somewhere. Most probably the Test-Server used for the Integration Tests doesn't have this kind of caching. I will see, where the error comes from, but I can't give a timeline.

My best guess at the moment is, that it is located somewhere when adding the `AuthFilter` to the ASP.NET Core Pipeline:

<img src="https://github.com/bytefish/ODataAuthorization/assets/239373/56a718b6-0d38-47f0-bb9f-f8dc89c642c5" width="500">

If I execute both requests, step into the second request and evaluate the current descriptors on the controller I can see the previous AuthFilter still hanging around:

<img src="https://github.com/bytefish/ODataAuthorization/assets/239373/729b44be-70c6-493e-b5fa-768201f89d7e" width="500">

And it only has 1 Permission it has to check, although we expect 2...

The obvious thing to do is, to remove the `AuthorizeFilter` and add it again:

<img src="https://github.com/bytefish/ODataAuthorization/assets/239373/a4ec9497-d564-48ec-ad4d-00333046b2da" width="500">

And when exiting the method, we can debug to the last statement and see, that the correct `AuthorizeFilter` has been set on the Controller. And after this we basically keep on executing the Request:

<img src="https://github.com/bytefish/ODataAuthorization/assets/239373/d9e2ca23-5438-4cbe-b341-6c1cfdb4cb9b" width="500">

This is where it gets interesting. The ASP.NET Core Pipeline passes us the wrong Requirement:

<img src="https://github.com/bytefish/ODataAuthorization/assets/239373/92de40b3-19f4-4d9d-b2e7-58478fba1350" width="500">

So not only the `AuthorizeFilter` context is cached, but also the Requirement.

Further digging into the behavior of ASP.NET Core MVC, we can see, that it caches the filters. So probably, our filter that we have removed and added isn't used at all and instead the cached one. We confirm this:

<img src="https://github.com/bytefish/ODataAuthorization/assets/239373/c0f20786-e7b2-425a-9c9e-d08c8dacb1ff" width="500">

**Comment by bytefish** [comment]
I have reworked how the Filter is built and applied. I misunderstood how "ASP.NET Core MVC" Filter differ from the "Classic ASP.NET MVC" Filters. In ASP.NET Core the Filters for a Controller are cached and even removing and adding them changes nothing... or leads to all kinds of threading issues. I now implemented an `IFilterProvider` (`ODataAuthorizeFilterProvider`) instead, which is responsible for inspecting the request and creating the AuthorizationFilter based on the current Request.

As soon as the 1.1.0 is indexed by NuGet, I will give your example a try. If I reference the ODataAuthorization Library directly right now, then the script returns the 403 for the second call:

```
PS C:\Users\philipp\source\repos\bytefish\ODataAuthorization.Sample\Powershell> .\ODataQueries.ps1
OData Query #1: http://localhost:5124/odata/Products
@{Id=1; Name=Macbook M1; Price=3000; AddressId=1} @{Id=2; Name=Macbook M2; Price=3500; AddressId=1} @{Id=3; Name=iPhone 14; Price=1400; AddressId=1}

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Users\philipp\source\repos\bytefish\ODataAuthorization.Sample\Powershell\ODataQueries.ps1:48 char:33
+ ... sResponse = Invoke-RestMethod -Uri "http://localhost:5124/odata/Produ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

OData Query #2: http://localhost:5124/odata/Products($expand=Address)

```

**Comment by ika18** [comment]
@bytefish 
Thanks for your investigation and very detailed explanation. I will have a try on my side.
Appreciate it!

**Comment by bytefish** [comment]
I made a PR to your repository. You could merge it and give it a try. 👍

**Comment by bytefish** [comment]
@ika18 Could you clarify the license of your example project. I would like to add it to the samples directory in this repository. Full credit is going to you.

**Comment by ika18** [comment]
> @ika18 Could you clarify the license of your example project. I would like to add it to the samples directory in this repository. Full credit is going to you.

Sure, I have created MIT license for my example project. https://github.com/ika18/ODataAuthorization.Sample/blob/main/LICENSE
Is that ok?

I'm also glad that you will add my example.

**Comment by bytefish** [comment]
Great! ❤️

**Comment by ika18** [comment]
Should I close this issue?

**Comment by bytefish** [comment]
Let’s leave it open until I merged your example. :)

**Comment by bytefish** [comment]
I have added your example to:

* https://github.com/bytefish/ODataAuthorization/tree/main/samples/JwtAuthenticationExample

Please let me know, if you think something is missing in it. 👍
